---
defaults:
  defaults: &defaults
    working_directory: '/go/src/github.com/influxdata/telegraf'
  go-1_9: &go-1_9
    docker:
      - image: 'circleci/golang:1.9.7'
  go-1_10: &go-1_10
    docker:
      - image: 'circleci/golang:1.10.3'

version: 2
jobs:
  deps:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: './scripts/getdep'
      - run: 'make deps'
      - save_cache:
          name: 'vendored deps'
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - './vendor'
      - persist_to_workspace:
          root: '/go/src'
          paths:
            - '*'

  test-go-1.9:
    <<: [ *defaults, *go-1_9 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make check'
      - run: 'make test'
  test-go-1.9-386:
    <<: [ *defaults, *go-1_9 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'
  test-go-1.10:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'make check'
      - run: 'make test'
  test-go-1.10-386:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'

  release:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: './scripts/release.sh'
      - store_artifacts:
          path: './artifacts'
          destination: '.'
  nightly:
    <<: [ *defaults, *go-1_10 ]
    steps:
      - attach_workspace:
          at: '/go/src'
      - run: './scripts/release.sh'
      - store_artifacts:
          path: './artifacts'
          destination: '.'

workflows:
  version: 2
  build_and_release:
    jobs:
      - 'deps'
      - 'test-go-1.9':
          requires:
            - 'deps'
      - 'test-go-1.9-386':
          requires:
            - 'deps'
      - 'test-go-1.10':
          requires:
            - 'deps'
      - 'test-go-1.10-386':
          requires:
            - 'deps'
      - 'release':
          requires:
            - 'test-go-1.9'
            - 'test-go-1.9-386'
            - 'test-go-1.10'
            - 'test-go-1.10-386'
  nightly:
    jobs:
      - 'deps'
      - 'test-go-1.9':
          requires:
            - 'deps'
      - 'test-go-1.9-386':
          requires:
            - 'deps'
      - 'test-go-1.10':
          requires:
            - 'deps'
      - 'test-go-1.10-386':
          requires:
            - 'deps'
      - 'nightly':
          requires:
            - 'test-go-1.9'
            - 'test-go-1.9-386'
            - 'test-go-1.10'
            - 'test-go-1.10-386'
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
